name: OfficialDsStatus-CS2 Build and Release

on:
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - created
  workflow_dispatch:      # 🎯 讓你可以隨時在網頁上手動點擊編譯

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: 'preview'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build Plugin
        run: dotnet build -c Release --no-restore -o ./addons/counterstrikesharp/plugins/OfficialDsStatus-CS2

      - name: Create ZIP Asset
        run: zip -r OfficialDsStatus-CS2.zip ./addons/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfficialDsStatus-CS2-純淨版
          path: ./OfficialDsStatus-CS2.zip

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./OfficialDsStatus-CS2.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
